// flow-typed signature: 4bcccce7662fdfe7483b3e20b90fce23
// flow-typed version: <<STUB>>/git-rev-sync_v^1.8.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'git-rev-sync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'git-rev-sync' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'git-rev-sync/examples/extended' {
  declare module.exports: any;
}

declare module 'git-rev-sync/examples/simple' {
  declare module.exports: any;
}

declare module 'git-rev-sync/tests/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'git-rev-sync/examples/extended.js' {
  declare module.exports: $Exports<'git-rev-sync/examples/extended'>;
}
declare module 'git-rev-sync/examples/simple.js' {
  declare module.exports: $Exports<'git-rev-sync/examples/simple'>;
}
declare module 'git-rev-sync/index' {
  declare module.exports: $Exports<'git-rev-sync'>;
}
declare module 'git-rev-sync/index.js' {
  declare module.exports: $Exports<'git-rev-sync'>;
}
declare module 'git-rev-sync/tests/index.js' {
  declare module.exports: $Exports<'git-rev-sync/tests/index'>;
}
